import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { useSigner, useProvider } from "wagmi";
import { Client } from "@xmtp/xmtp-js";
import { useState } from "react";

export default function Home() {
  const { data: signer } = useSigner();
  const [conversations, setConversations] = useState("");

  const sendMessage = async () => {
    try {
      const xmtp = await Client.create(signer);
      const allConversations = await xmtp.conversations.list();
      setConversations(allConversations);
      for (const conversation of allConversations) {
        console.log(`${conversation.peerAddress}`);
      }
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <button onClick={sendMessage}>Send Message</button>
        {conversations ? (
        <ul>
          {conversations.map((value, index) => {
            return <li key={index}>{value.peerAddress}</li>;
          })}
        </ul>
        ) : (<div></div>)}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
