import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { useSigner, useProvider } from "wagmi";
import { Client } from "@xmtp/xmtp-js";

export default function Home() {
  const getSignerOrProvider = async (needSigner = false) => {
    try {
      const provider = useProvider();
      if ((needSigner = true)) {
        const { data: signer } = useSigner();
        return signer;
      }
      return provider;
    } catch (error) {
      console.log(error);
    }
  };

  const sendMessage = async () => {
    try {
      const signer = await getSignerOrProvider(true);
      const xmtp = await Client.create(signer);
      const conversation = await xmtp.conversations.newConversation(
        "0x4a37dF8B8E1a79c364abB7C86716B5a8E435dC80"
      );
      const messages = await conversation.messages();
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <button onClick={sendMessage}>Send Message</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
